### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by ryancwalsh** [jakcodex/seasalt#1]
I've spent 2 days trying to get anything to work in libsodium.js. And I've remained stuck. (I wonder if you have ideas about what I'm doing wrong? https://github.com/jedisct1/libsodium.js/issues/120#issuecomment-412290152)

Also, your repo looks super interesting!

But when running `npm install https://github.com/jakcodex/seasalt.git`, I get this error:
`fatal: remote error: npm ERR!   jedisct1/libsodium.js.git^0.7.3 is not a valid repository name`

https://github.com/jakcodex/seasalt/blob/4de3e1dc70dc15c3ceb608b5b4207a5ecbf959c2/package.json#L7

Thanks.

**Comment by jakcodex** [comment]
Eek, sorry. I just saw you today. Yeah, the dependency is broken and I need to fix that. Did you happen to in your fork?

To answer the question, presently this library is only tested in browsers. I haven't gone down the nodejs path yet, tho I will at some point. If you check out seasalt.html, you can see how I load it into the script.

https://github.com/jakcodex/seasalt/blob/master/seasalt.html#L204

There and the following 15 lines should show. In a nutshell:

```html
<script src="vendor/sodium.sumo.js" async></script>
<script language="JavaScript">
        window.sodium = {
            onload: function() {
                //  sodium is now available here
                //  and SeaSalt classes will be fully usable
            }
        }
</script>
```

Note: Sumo version is only needed if you wish to use SeaSalt classes that require it (password hashing and such).

**Comment by ryancwalsh** [comment]
I didn't end up using Seasalt.

**Comment by jakcodex** [comment]
No worries. Good day to you :)
